// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251113133128_FixSeeds")]
    partial class FixSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("BookGenre");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 2,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 3,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 4,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 5,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 6,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 7,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 8,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 9,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 10,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 11,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 12,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 13,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 14,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 15,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 16,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 17,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 18,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 19,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 20,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 21,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 22,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 23,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 24,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 26,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 27,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 28,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 25,
                            GenreId = 3
                        },
                        new
                        {
                            BookId = 35,
                            GenreId = 3
                        },
                        new
                        {
                            BookId = 36,
                            GenreId = 3
                        },
                        new
                        {
                            BookId = 37,
                            GenreId = 3
                        },
                        new
                        {
                            BookId = 38,
                            GenreId = 3
                        },
                        new
                        {
                            BookId = 39,
                            GenreId = 3
                        },
                        new
                        {
                            BookId = 40,
                            GenreId = 3
                        },
                        new
                        {
                            BookId = 29,
                            GenreId = 5
                        },
                        new
                        {
                            BookId = 29,
                            GenreId = 2
                        },
                        new
                        {
                            BookId = 30,
                            GenreId = 5
                        },
                        new
                        {
                            BookId = 30,
                            GenreId = 2
                        },
                        new
                        {
                            BookId = 31,
                            GenreId = 5
                        },
                        new
                        {
                            BookId = 31,
                            GenreId = 2
                        },
                        new
                        {
                            BookId = 32,
                            GenreId = 5
                        },
                        new
                        {
                            BookId = 32,
                            GenreId = 2
                        },
                        new
                        {
                            BookId = 33,
                            GenreId = 5
                        },
                        new
                        {
                            BookId = 33,
                            GenreId = 2
                        },
                        new
                        {
                            BookId = 34,
                            GenreId = 5
                        },
                        new
                        {
                            BookId = 34,
                            GenreId = 2
                        });
                });

            modelBuilder.Entity("Domain.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "John Ronald Reuel Tolkien (1892-1973) fue un filólogo y escritor británico, autor de obras como El hobbit y El Señor de los Anillos. Nacido en Bloemfontein (Sudáfrica) y criado en Inglaterra, se casó con Edith Bratt en 1916, con quien tuvo cuatro hijos. Vivió con ella hasta quedar viudo en 1971.",
                            Name = "J. R. R. Tolkien"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Agatha Christie (1890-1976) fue una escritora británica de novelas policiales, considerada la reina del misterio. Nacida en Torquay, Inglaterra, se casó primero con Archibald Christie, con quien tuvo una hija, Rosalind. Tras divorciarse, se casó con el arqueólogo Max Mallowan, con quien permaneció casada hasta su muerte.",
                            Name = "Agatha Christie"
                        },
                        new
                        {
                            Id = 3,
                            Description = "George Orwell (1903-1950), seudónimo de Eric Arthur Blair, fue un escritor y periodista británico conocido por Rebelión en la granja y 1984. Nació en la India británica y creció en Inglaterra. Se casó con Eileen O’Shaughnessy, quien falleció en 1945, quedando viudo. Más tarde se casó con Sonia Brownell y adoptó un hijo, Richard.",
                            Name = "George Orwell"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Rick Riordan (1964) es un escritor estadounidense de fantasía juvenil, creador de la saga Percy Jackson. Nació en San Antonio, Texas. Está casado con Becky (Rebecca) Klahn desde 1985 y tienen dos hijos, Haley y Patrick. Ha trabajado como profesor antes de dedicarse por completo a la escritura.",
                            Name = "Rick Riordan"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Cassandra Clare (1973), cuyo nombre real es Judith Rumelt, es una escritora estadounidense de fantasía urbana, conocida por la saga Cazadores de Sombras. Nació de padres estadounidenses en Teherán y creció en distintos países. Está casada con Joshua Lewis; no tienen hijos y viven en Massachusetts con varios gatos.",
                            Name = "Cassandra Clare"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Gaston Leroux (1868-1927) fue un novelista y periodista francés, célebre por El Fantasma de la Ópera. Nació en París y trabajó como reportero antes de dedicarse a la ficción. Se casó con Marie Lefranc y, tras enviudar, con Jeanne Cayatte; tuvo dos hijos y pasó sus últimos años en Niza.",
                            Name = "Gaston Leroux"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Antoine de Saint-Exupéry (1900-1944) fue un aviador y escritor francés, autor de El Principito. Nació en Lyon en una familia de pequeña nobleza. Se casó con la artista salvadoreña Consuelo Suncín; la pareja no tuvo hijos. Desapareció en una misión aérea durante la Segunda Guerra Mundial.",
                            Name = "Antoine de Saint-Exupéry"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Gabriel García Márquez (1927-2014) fue un escritor y periodista colombiano, figura central del realismo mágico y autor de Cien años de soledad. Nació en Aracataca, Colombia. Se casó con Mercedes Barcha en 1958 y tuvieron dos hijos, Rodrigo y Gonzalo. Vivió entre América Latina, México y Europa.",
                            Name = "Gabriel García Márquez"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Jules Verne (1828-1905) fue un novelista francés pionero de la ciencia ficción, conocido por obras como La vuelta al mundo en 80 días y Veinte mil leguas de viaje submarino. Nacido en Nantes, se casó con Honorine Morel en 1857, con quien tuvo un hijo, Michel, y fue padrastro de sus dos hijas.",
                            Name = "Jules Verne"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Suzanne Collins (1962) es una escritora estadounidense, creadora de la trilogía Los Juegos del Hambre. Nació en Hartford, Connecticut. Estuvo casada muchos años con el actor Charles “Cap” Pryor y es madre de dos hijos, Charlie e Isabel. Comenzó su carrera escribiendo para televisión infantil.",
                            Name = "Suzanne Collins"
                        },
                        new
                        {
                            Id = 11,
                            Description = "James Dashner (1972) es un escritor estadounidense de literatura juvenil y ciencia ficción, conocido por la saga The Maze Runner. Nació en Georgia y se crió en una familia numerosa. Está casado con Lynette Anderson y tienen cuatro hijos; viven en Utah.",
                            Name = "James Dashner"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Stephen King (1947) es un escritor estadounidense, maestro del terror y el suspense, autor de It, El resplandor y muchas otras novelas. Nació en Portland, Maine. Está casado con la escritora Tabitha Spruce desde 1971 y tienen tres hijos, Naomi, Joe y Owen.",
                            Name = "Stephen King"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pages")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 4,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1481567822i/7816926.jpg",
                            Pages = 416,
                            Summary = "Percy Jackson descubre que es hijo de un dios griego y debe emprender una misión para recuperar el rayo maestro de Zeus y evitar una guerra entre los dioses del Olimpo.",
                            Title = "El ladrón del rayo"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 4,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1451102362i/8620262.jpg",
                            Pages = 279,
                            Summary = "Percy y sus amigos viajan al peligroso Mar de los Monstruos para encontrar el Vellocino de Oro y salvar el Campamento Mestizo de la destrucción.",
                            Title = "El mar de los monstruos"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 4,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1297123292i/8267049.jpg",
                            Pages = 352,
                            Summary = "Percy se une a una nueva misión para rescatar a un semidiós desaparecido y a la diosa Artemisa, enfrentándose a criaturas cada vez más peligrosas.",
                            Title = "La maldición del titán"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1511187879i/8267056.jpg",
                            Pages = 361,
                            Summary = "Percy y sus aliados se adentran en el Laberinto de Dédalo para impedir que el ejército de Cronos encuentre una entrada secreta al Campamento Mestizo.",
                            Title = "La batalla del laberinto"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 4,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1317254851i/8267073.jpg",
                            Pages = 381,
                            Summary = "Percy lidera a los semidioses en la batalla final contra Cronos en las calles de Nueva York, donde se decide el destino del Olimpo.",
                            Title = "El último héroe del Olimpo"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 4,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1359821070i/17188896.jpg",
                            Pages = 576,
                            Summary = "Jason despierta sin memoria en un autobús escolar y, junto a Piper y Leo, descubre que es un semidiós y que debe rescatar a Hera para evitar una nueva amenaza.",
                            Title = "El héroe perdido"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 4,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1369923685i/17999618.jpg",
                            Pages = 521,
                            Summary = "Percy, sin recuerdos de su pasado, llega a un campamento romano y se une a Hazel y Frank en una peligrosa búsqueda para liberar a la Muerte.",
                            Title = "El hijo de Neptuno"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 4,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1397161148i/18209368.jpg",
                            Pages = 586,
                            Summary = "Siete semidioses, griegos y romanos, deben unirse para viajar a Roma, seguir la pista de la marca de Atenea y enfrentar a los gigantes de Gea.",
                            Title = "La marca de Atenea"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 4,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388174908i/19452719.jpg",
                            Pages = 597,
                            Summary = "Mientras Percy y Annabeth luchan por sobrevivir en el Tártaro, el resto de los semidioses intenta llegar a la Casa de Hades para cerrar las Puertas de la Muerte.",
                            Title = "La casa de Hades"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 4,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1319186494i/12929218.jpg",
                            Pages = 528,
                            Summary = "Los hermanos Carter y Sadie Kane descubren que son herederos de la magia de los faraones y deben detener a un dios egipcio que amenaza con destruir el mundo.",
                            Title = "La pirámide roja"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 4,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1332092735i/13152321.jpg",
                            Pages = 452,
                            Summary = "Carter y Sadie continúan su entrenamiento mágico mientras buscan despertar al dios Ra para enfrentar a la serpiente del caos, Apofis.",
                            Title = "El trono de fuego"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 4,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1348735646i/16049484.jpg",
                            Pages = 406,
                            Summary = "Los Kane deben reunir aliados y lanzar un arriesgado plan para derrotar definitivamente a Apofis antes de que sumerja al mundo en el caos.",
                            Title = "La sombra de la serpiente"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 5,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1376162468i/9025186.jpg",
                            Pages = 485,
                            Summary = "Clary Fray descubre el mundo oculto de los Cazadores de Sombras cuando presencia un asesinato que solo ella parece ver y comienza a desentrañar secretos sobre su familia.",
                            Title = "Ciudad de huesos"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 5,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1290632930i/8398780.jpg",
                            Pages = 453,
                            Summary = "Mientras el mundo subterráneo está en peligro por los planes de Valentine, Clary intenta proteger a su familia y sus amigos mientras lidia con nuevos poderes y sentimientos.",
                            Title = "Ciudad de cenizas"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 5,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1293514063i/8510934.jpg",
                            Pages = 541,
                            Summary = "Clary viaja a la ciudad de Idris en busca de una cura para su madre y se ve envuelta en una guerra que definirá el futuro de los Cazadores de Sombras y los subterráneos.",
                            Title = "Ciudad de cristal"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 5,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1296855516i/10388376.jpg",
                            Pages = 425,
                            Summary = "Tras la aparente paz, empiezan a aparecer cuerpos de Cazadores de Sombras asesinados y una nueva amenaza se cierne sobre Nueva York, poniendo a prueba las lealtades de todos.",
                            Title = "Ciudad de los ángeles caídos"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 5,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1343424226i/15722810.jpg",
                            Pages = 535,
                            Summary = "Jace ha desaparecido y parece estar ligado a Sebastian; Clary se infiltra en sus planes para salvarlo, mientras el resto del grupo busca una forma de romper ese vínculo.",
                            Title = "Ciudad de las almas perdidas"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 5,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1402362254i/22450140.jpg",
                            Pages = 725,
                            Summary = "La batalla final contra Sebastian se desata y los Cazadores de Sombras deben arriesgarlo todo para evitar la destrucción de su mundo.",
                            Title = "Ciudad del fuego celestial"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 5,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1324687382i/9606604.jpg",
                            Pages = 479,
                            Summary = "En la Londres victoriana, Tessa Gray descubre que puede cambiar de forma y se ve envuelta en una conspiración mágica junto a los Cazadores de Sombras del Instituto de Londres.",
                            Title = "Ángel mecánico"
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 5,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1329482768i/13482202.jpg",
                            Pages = 498,
                            Summary = "Mientras el enemigo Mortmain se acerca a ejecutar su plan, Tessa debe enfrentarse a su pasado y a sus sentimientos por Will y Jem.",
                            Title = "Príncipe mecánico"
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 5,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1364075211i/17670710.jpg",
                            Pages = 567,
                            Summary = "La trilogía de los Orígenes culmina con un enfrentamiento decisivo contra Mortmain y decisiones que marcarán a varias generaciones de Cazadores de Sombras.",
                            Title = "Princesa mecánica"
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 5,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1459625664i/29762865.jpg",
                            Pages = 688,
                            Summary = "En Los Ángeles, Emma Carstairs investiga la muerte de sus padres mientras se ve envuelta en un caso de asesinatos conectados con magia oscura y secretos del pasado.",
                            Title = "Lady Midnight"
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 5,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1498754479i/35544729.jpg",
                            Pages = 699,
                            Summary = "Emma y los Blackthorn deben enfrentar las consecuencias de sus decisiones, mientras nuevas fuerzas oscuras amenazan a los Cazadores de Sombras.",
                            Title = "El señor de las sombras"
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 5,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1709644904i/43382020.jpg",
                            Pages = 893,
                            Summary = "Tras una tragedia devastadora, el mundo de los Cazadores de Sombras se fragmenta y la familia Blackthorn debe evitar una guerra civil en el más alto nivel.",
                            Title = "La reina del aire y la oscuridad"
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 6,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1560671713l/50833391.jpg",
                            Pages = 360,
                            Summary = "En la Ópera de París, una misteriosa figura que habita en los pasadizos subterráneos se obsesiona con la joven soprano Christine Daaé, desencadenando una historia de amor, miedo y tragedia.",
                            Title = "El Fantasma de la Ópera"
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 7,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1328876389i/866618.jpg",
                            Pages = 360,
                            Summary = "Un aviador perdido en el desierto se encuentra con un pequeño príncipe venido de otro planeta, que le cuenta sus viajes por distintos mundos y le recuerda la importancia de la amistad y lo esencial.",
                            Title = "El Principito"
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 8,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1347626503i/370523.jpg",
                            Pages = 132,
                            Summary = "La novela recorre la historia de la familia Buendía en el pueblo ficticio de Macondo, mezclando realidad y fantasía para mostrar el peso del tiempo, la memoria y la soledad.",
                            Title = "100 años de soledad"
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 9,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1519022835i/38617139.jpg",
                            Pages = 187,
                            Summary = "El metódico caballero inglés Phileas Fogg apuesta que puede dar la vuelta al mundo en 80 días, emprende un viaje contrarreloj y enfrenta todo tipo de imprevistos.",
                            Title = "La vuelta al mundo en 80 dias"
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 10,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1335891621i/6596839.jpg",
                            Pages = 374,
                            Summary = "En un futuro distópico, Katniss Everdeen se ofrece voluntaria para reemplazar a su hermana en unos juegos televisados a muerte organizados por el Capitolio.",
                            Title = "Los Juegos del Hambre"
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 10,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1268836422i/7776692.jpg",
                            Pages = 391,
                            Summary = "Tras ganar los Juegos, Katniss se convierte en símbolo de rebeldía y es obligada a volver a la arena en una edición especial que enciende aún más la revolución.",
                            Title = "En llamas"
                        },
                        new
                        {
                            Id = 31,
                            AuthorId = 10,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1347835499i/8322565.jpg",
                            Pages = 390,
                            Summary = "Katniss se une abiertamente a la rebelión contra el Capitolio y debe decidir hasta dónde está dispuesta a llegar para cambiar el sistema.",
                            Title = "Sinsajo"
                        },
                        new
                        {
                            Id = 32,
                            AuthorId = 11,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1354770985i/9167899.jpg",
                            Pages = 384,
                            Summary = "Thomas despierta en un ascensor sin recuerdos y llega al Claro, rodeado por un gigantesco laberinto cambiante que él y otros chicos deben resolver para sobrevivir.",
                            Title = "Correr o morir"
                        },
                        new
                        {
                            Id = 33,
                            AuthorId = 11,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1354771494i/12043291.jpg",
                            Pages = 362,
                            Summary = "Tras escapar del Laberinto, Thomas y los demás son lanzados a un desierto ardiente lleno de peligros, donde deben superar una nueva prueba mortal.",
                            Title = "Prueba de fuego"
                        },
                        new
                        {
                            Id = 34,
                            AuthorId = 11,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1339216613i/15677818.jpg",
                            Pages = 325,
                            Summary = "Thomas se enfrenta a la verdad sobre CRUEL, las pruebas y la enfermedad llamada El Destello, en una última misión para decidir el destino de la humanidad.",
                            Title = "La Cura Mortal"
                        },
                        new
                        {
                            Id = 35,
                            AuthorId = 12,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1334416842i/830502.jpg",
                            Pages = 1184,
                            Summary = "Un grupo de amigos se enfrenta de niños y luego de adultos a una entidad maligna que adopta la forma de un payaso llamado Pennywise en el pueblo de Derry.",
                            Title = "It"
                        },
                        new
                        {
                            Id = 36,
                            AuthorId = 12,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1166254258i/10592.jpg",
                            Pages = 272,
                            Summary = "Carrie White, una adolescente marginada con poderes telequinéticos, es llevada al límite por el acoso de sus compañeros y el fanatismo de su madre.",
                            Title = "Carrie"
                        },
                        new
                        {
                            Id = 37,
                            AuthorId = 12,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1339551789i/15703424.jpg",
                            Pages = 592,
                            Summary = "En el corredor de la muerte de una prisión sureña, un guardia conoce a un condenado con habilidades sobrenaturales que cambian su visión sobre la justicia.",
                            Title = "La Milla Verde"
                        },
                        new
                        {
                            Id = 38,
                            AuthorId = 12,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1281058680i/3389955.jpg",
                            Pages = 497,
                            Summary = "Jack Torrance acepta cuidar un hotel aislado durante el invierno junto a su familia, pero fuerzas oscuras comienzan a afectar su mente.",
                            Title = "El Resplandor"
                        },
                        new
                        {
                            Id = 39,
                            AuthorId = 12,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1376955133i/18359794.jpg",
                            Pages = 608,
                            Summary = "Danny Torrance, ya adulto, lucha con sus traumas y su alcoholismo mientras protege a una niña con poderes psíquicos de un grupo que se alimenta de niños como ella.",
                            Title = "Doctor Sueño"
                        },
                        new
                        {
                            Id = 40,
                            AuthorId = 2,
                            CoverUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1507482254i/36375809.jpg",
                            Pages = 196,
                            Summary = "Durante un lujoso viaje en tren, el detective Hércules Poirot debe resolver el asesinato de un pasajero mientras el Orient Express está detenido por la nieve.",
                            Title = "Asesinato en el Orient Express"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GenreName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreName = "Fantasía"
                        },
                        new
                        {
                            Id = 2,
                            GenreName = "Ciencia Ficción"
                        },
                        new
                        {
                            Id = 3,
                            GenreName = "Misterio"
                        },
                        new
                        {
                            Id = 4,
                            GenreName = "No Ficción"
                        },
                        new
                        {
                            Id = 5,
                            GenreName = "Distopía"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Lecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("BookTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinishDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Lectures");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarUrl = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Email = "manu@gmail.com",
                            Password = "123456",
                            Role = 2,
                            Username = "Manu"
                        },
                        new
                        {
                            Id = 2,
                            AvatarUrl = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Email = "mati@gmail.com",
                            Password = "123456",
                            Role = 2,
                            Username = "Mati"
                        });
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.HasOne("Domain.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Book", b =>
                {
                    b.HasOne("Domain.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Domain.Entities.Lecture", b =>
                {
                    b.HasOne("Domain.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Lectures")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Lectures");
                });
#pragma warning restore 612, 618
        }
    }
}
